# cargo release
pre-release-commit-message = "Release {{version}} ðŸŽ‰"
pre-release-replacements = [ {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"}, {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"} ]
